// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://naqestrcommcpbspwuna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hcWVzdHJjb21tY3Bic3B3dW5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMjk4MTQsImV4cCI6MjA2NjcwNTgxNH0.S7gvFjd436deKHlpEmV5OmdE8j6wtMFsWiEemvYbslI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);